import type { NextPage } from "next";
import Head from "next/head";
import { PlayerModel } from "../App/models/PlayerModel";
import { getPlayer } from "../App/services/player.service";
import HeroEqupiment from "../App/views/Profile/components/HeroEquipment";
import HeroInventory from "../App/views/Profile/components/HeroInventory";

type Props = {
  player: PlayerModel;
};

export const getStaticProps = async () => {
  const response = await getPlayer();
  console.log(response);

  return {
    props: {
      player: response,
    },
  };
};

const Home: NextPage<Props> = (props: Props) => {
  return (
    <>
      <Head>
        <title>WebBrowserGame</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex flex-col justify-center items-center w-full h-full ">
        <HeroEqupiment />
        <HeroInventory />
      </section>
    </>
  );
};

export default Home;
